# Generated by Django 4.2.9 on 2024-01-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leisure_log_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="url", new_name="link",),
    ]
