# Generated by Django 4.2.9 on 2024-02-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leisure_log_app", "0002_rename_url_post_link"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="link", new_name="url",),
    ]
